Update cisco_nxos_show_interface_description.textfsm
Running command on NX-OS 56128P, received error due to speed column returning "--" for a san-port-channel interface. Updated SPEED type to allow string.

Error: State Error raised. Rule Line: 16. Input Line: san-port-channel 3  --